### ISSUE TITLE
Wishlist not opening

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#10]
The wishlist is not opening.

![image](https://user-images.githubusercontent.com/97726944/167837479-283fabdc-1429-4644-a4ca-0e0460cededa.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans 
![image](https://user-images.githubusercontent.com/100207984/168375318-531db0d5-39d5-4f0a-b940-01a5d025d2cb.png)

fixed

**Comment by Shoaibans** [comment]
Wishlist is not opening nor coming on products & product page button
