### ISSUE TITLE
Policies in search page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#11]
The policies are also coming in the search page along with the products.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/search?q=head&options%5Bprefix%5D=last
![image](https://user-images.githubusercontent.com/97726944/167837789-1e533d35-1250-4f16-85c4-af56a6e33d81.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans  issue fixed
![image](https://user-images.githubusercontent.com/100207984/167936518-56ab379f-8e23-4a61-8648-0dbaed9d58b6.png)
.

**Comment by Shoaibans** [comment]
Now there is a blank space coming in place of policies.

![image](https://user-images.githubusercontent.com/97726944/168041997-c3f72942-b2e0-4787-b0f9-f99dd14189b9.png)

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/168914949-a9a95548-f4f6-4db3-b707-3fecddd05be7.png)
fixed
