### ISSUE TITLE
Filters in search page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#12]
Search page is having different filter layout & the filter dropdowns are coming below the products.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/search?q=head&options%5Bprefix%5D=last
![image](https://user-images.githubusercontent.com/97726944/167838146-4e8baed3-b455-4fd9-999d-d6f665ceb697.png)

**Comment by rajatsinghcedcoss** [comment]
done 
![image](https://user-images.githubusercontent.com/96044645/167840248-6f28cbef-9798-4aaa-ace8-ae8b5d859b5e.png)
