### ISSUE TITLE
Missing wishlist icon

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#13]
The wishlist icon is not coming on the products in collection page.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/collections/pet-accessories
![image](https://user-images.githubusercontent.com/97726944/167838502-9762d33f-e98e-45e3-92db-f740f58cbadc.png)

**Comment by devAlokTripathi** [comment]
fixed @Shoaibans

**Comment by Shoaibans** [comment]
Now the wishlist icon is not coming in mobile & iPad.
![image](https://user-images.githubusercontent.com/97726944/168062555-c252d1e0-a4f9-4514-9f3c-dd3b44941d0b.png)

**Comment by devAlokTripathi** [comment]
wishlist free subscription expire so we are unable to see the wishlist icon and working . when client purchased the plan thwen it will work .
