### ISSUE TITLE
Quantity field in product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#15]
The quantity field is going empty in product page.

![image](https://user-images.githubusercontent.com/97726944/167840213-5019e7e5-7db6-4227-89d6-3b0883b5d9f4.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans fixed.

**Comment by devAlokTripathi** [comment]
![Uploading image.png…]()
