### ISSUE TITLE
Sortby in collection/search page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#16]
The sortby filters are coming very close to the left side of the box.

![image](https://user-images.githubusercontent.com/97726944/167840817-8ebfe44d-0a9a-4316-a0ad-0545d449e8ee.png)

**Comment by rajatsinghcedcoss** [comment]
![image](https://user-images.githubusercontent.com/96044645/167844608-cac61eae-4d3c-435f-9531-83deb1193b81.png)
Done
