### ISSUE TITLE
Cross button/symbol in announcement bar

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#17]
The cross button/symbol in announcement bar is not clearly visible.

![image](https://user-images.githubusercontent.com/97726944/167841305-ccd8b142-27ff-49ee-8245-51686785584f.png)

**Comment by rajatsinghcedcoss** [comment]
Done

**Comment by Shoaibans** [comment]
Hand cursor should come on hover @rajatsinghcedcoss

**Comment by rajatsinghcedcoss** [comment]
fixed @Shoaibans
