### ISSUE TITLE
Missing button

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#18]
Add to wishlist button is missing from the product page while we have used wishlist for the store.

![image](https://user-images.githubusercontent.com/97726944/167841596-06a9b12e-7669-4bb6-982c-1c1a05267c37.png)

**Comment by Shoaibans** [comment]
The button should be above the payment icons.

![image](https://user-images.githubusercontent.com/97726944/168043472-897afda0-6129-4448-8095-05680f47cc05.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
![image](https://user-images.githubusercontent.com/96044645/168047194-3e341917-54f5-466d-9690-2c17d66b0020.png)

@Shoaibans

**Comment by Shoaibans** [comment]
Now the payment icons are missing. (if required on product page)
![image](https://user-images.githubusercontent.com/97726944/168067456-8d58bd36-677b-4860-b2bd-05b1dd1c3a7a.png)

**Comment by Shoaibans** [comment]
Now the payment icons are not coming in product page.  
![image](https://user-images.githubusercontent.com/97726944/168067456-8d58bd36-677b-4860-b2bd-05b1dd1c3a7a.png)

**Comment by devAlokTripathi** [comment]
dynamically coming its not an issue .
