### ISSUE TITLE
Missing wishlist icon from product page You may also like section

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#19]
The wishlist icon is missing from product page You may also like section.
![image](https://user-images.githubusercontent.com/97726944/167842207-ca074059-707b-464a-a0fc-c20240a156ac.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans  when theme is live then it show the icon .
![image](https://user-images.githubusercontent.com/100207984/167937873-ba4d370c-3c56-4de3-b448-a8e6d6d21442.png)
![image](https://user-images.githubusercontent.com/100207984/167938010-8d160b40-3aac-4f1a-b74d-e37f60fd1f70.png)
