### ISSUE TITLE
Button linking in Announcement bar

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#2]
The button used in announcement  bar is linked to the homepage. It should be linked to the collection page.

![image](https://user-images.githubusercontent.com/97726944/167829417-c2b63985-1e11-4e6d-bd14-2baf4c46ce81.png)

**Comment by devAlokTripathi** [comment]
not showing in the header please check. fixed.

**Comment by Shoaibans** [comment]
Announcement bar removed.
