### ISSUE TITLE
Spacing in Hamburger

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#21]
We can reduce the spacing in hamburger.
**SUGGESTION**
![image](https://user-images.githubusercontent.com/97726944/167844294-7729b80e-9b08-4567-a244-35d2a145c174.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
![image](https://user-images.githubusercontent.com/96044645/168048995-6c1da41b-6fb3-491a-a059-f806c8402e37.png)

@Shoaibans

**Comment by Shoaibans** [comment]
This spacing can be reduced.
![image](https://user-images.githubusercontent.com/97726944/168051513-8b89f85e-fb58-44a8-862e-eb98d36b10e2.png)

**Comment by rajatsinghcedcoss** [comment]
fixed 
![image](https://user-images.githubusercontent.com/96044645/168052915-5fbbd13b-daf3-4c0a-a7e7-c35aec15e52b.png)

@Shoaibans
