### ISSUE TITLE
Cropped collection images

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#22]
The collection images looks like they are cropped.

![image](https://user-images.githubusercontent.com/97726944/167845320-4cadde19-829b-4c76-85f8-463ed4f76a09.png)

**Comment by rajatsinghcedcoss** [comment]
fixed

![image](https://user-images.githubusercontent.com/96044645/167999073-7d49a715-ad93-46b4-b069-6f1aeae9c331.png)
