### ISSUE TITLE
Small collection images

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#23]
The collection images are coming small in Mobile & iPad.
Video:
https://www.awesomescreenshot.com/video/8846252?key=e09da44eee45bacecbf415cbcbf8d256

**Comment by rajatsinghcedcoss** [comment]
mobile fixed in ipad it is ok
https://www.awesomescreenshot.com/video/8860819?key=d99a9321eba3cc12aa65963da2182408
