### ISSUE TITLE
Spacing in FAQ page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#24]
The spacing can be reduced in FAQ page above the footer section.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/pages/faqs
![image](https://user-images.githubusercontent.com/97726944/167846308-8d64a019-b1ec-4007-97fc-da072be5654d.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
![image](https://user-images.githubusercontent.com/96044645/168001077-8c2ebef6-473e-4f37-b5d5-081ae4152eb4.png)
