### ISSUE TITLE
Random checkmark reflection

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#25]
A random checkmark reflection is coming in all the views.

![image](https://user-images.githubusercontent.com/97726944/167846772-260a7830-a38f-4734-aaf8-4d0f7f3f80b7.png)
Video: https://www.awesomescreenshot.com/video/8846353?key=10d89a3f76e3f8313c3c35b989739118

**Comment by rajatsinghcedcoss** [comment]
there is no checkmark reflection  in my end
https://www.awesomescreenshot.com/video/8846800?key=9420db0c1c554f046c249080b0c4fe69

**Comment by Shoaibans** [comment]
Pls check the video & open the preview in private/ incognito window.

https://www.awesomescreenshot.com/video/8866560?key=dedad33b8680ab4ad22a776d3a1b3c4f

**Comment by rajatsinghcedcoss** [comment]
@Shoaibans Done
