### ISSUE TITLE
Add to cart button is not working in product page You May also like section

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#26]
The add to cart button given on the products are not working in You may also like section.

![image](https://user-images.githubusercontent.com/97726944/167847466-566d04ff-6356-4555-b4f6-f3cdb2f3270c.png)

**Comment by Shoaibans** [comment]
Now the ATC on products is not working anywhere (Homepage, collection, search)

**Comment by devAlokTripathi** [comment]
@Shoaibans  fixed please check .
