### ISSUE TITLE
Search bar dropdown overlapping

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#27]
The search bar dropdown is overlapping with the products in Mobile & iPad.

![image](https://user-images.githubusercontent.com/97726944/167848373-10a718cb-ebd9-42f3-90c5-4af78a7658d9.png)

**Comment by rajatsinghcedcoss** [comment]
there is no overlapping in my end 
https://www.awesomescreenshot.com/video/8846604?key=b61c64e575e6971ad554701870b95308 #

**Comment by Shoaibans** [comment]
Check the video:
https://www.awesomescreenshot.com/video/8865929?key=98e2a508133606fe6dc62e2a5c5085cc

**Comment by rajatsinghcedcoss** [comment]
@Shoaibans fixed
![image](https://user-images.githubusercontent.com/96044645/168079371-01fa0e34-c6aa-4cc2-b371-2d4446d6dff6.png)
