### ISSUE TITLE
Collection names in collections page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#28]
The collection names are not coming proper in collections page (Mobile)
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/collections
![image](https://user-images.githubusercontent.com/97726944/167850419-3fdc202c-1259-4ead-ad1a-c05eba1c81d7.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
![image](https://user-images.githubusercontent.com/96044645/168004737-9c260fc1-4c1f-4826-9745-09017dfeab9e.png)

**Comment by Shoaibans** [comment]
Can give the collection name & arrow button in single line. & also in the homepage.
![image](https://user-images.githubusercontent.com/97726944/168049569-69670073-ae71-4d09-8022-751e38ee91a3.png)
Homepage:
![image](https://user-images.githubusercontent.com/97726944/168049775-83101e12-b6d7-4c44-9199-8e3f658037d1.png)

**Comment by rajatsinghcedcoss** [comment]
![image](https://user-images.githubusercontent.com/96044645/168055867-e729d24e-f522-4a8b-afc3-7148f5f13840.png)
fixed
@Shoaibans
