### ISSUE TITLE
Cropped product in banner

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#29]
Product images are cropping from the right in banners. (iPad)

![image](https://user-images.githubusercontent.com/97726944/167851390-ebd02098-ee91-42b0-b8fb-21f44db09ee5.png)
![image](https://user-images.githubusercontent.com/97726944/167851439-20c6375c-091b-42c7-ae6a-6c3470c2ad51.png)

**Comment by rajatsinghcedcoss** [comment]
fixed

![image](https://user-images.githubusercontent.com/96044645/167991046-87b3dac8-a1dc-49dd-a469-cc157bf31585.png)
![image](https://user-images.githubusercontent.com/96044645/167991144-4648cfb9-2075-4eca-b0e9-3c44ee7d5030.png)

**Comment by Shoaibans** [comment]
Now the text is coming over the product image.
![image](https://user-images.githubusercontent.com/97726944/168046981-5ebd5648-d097-4e62-a2fb-2daf2a0f0160.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
![image](https://user-images.githubusercontent.com/96044645/168050125-fa9ca89f-bef8-405c-955f-89f864cb263e.png)
@Shoaibans

**Comment by Shoaibans** [comment]
Now the banners are cropping more.
![image](https://user-images.githubusercontent.com/97726944/168063460-f7c925e9-5945-4159-ab8d-7f58e39fd563.png)
