### ISSUE TITLE
Missing collection Bg color

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#3]
The collection is not having Bg color as others in collections page
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/collections

![image](https://user-images.githubusercontent.com/97726944/167831112-79ec7361-d220-454e-b3a5-3a232e9df3d6.png)

**Comment by rajatsinghcedcoss** [comment]
This collection would be remove that's why there is no bg in it

**Comment by Shoaibans** [comment]
Collection removed
