### ISSUE TITLE
Announcement bar overlapping

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#30]
The announcement bar is overlapping with the filter pop up.

![image](https://user-images.githubusercontent.com/97726944/167852014-6437fba6-2c51-4d88-97e4-c212a65e4d54.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
![image](https://user-images.githubusercontent.com/96044645/168002748-def71e01-e800-4056-867d-d96774d932be.png)
