### ISSUE TITLE
Collection name in button

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#31]
The name should be All accessories instead of other accessories in homepage button, because the page is linked with all accessories collection page.
![image](https://user-images.githubusercontent.com/97726944/168052194-0df97914-316f-48d2-8303-f87706498ac1.png)

**Comment by rajatsinghcedcoss** [comment]
![image](https://user-images.githubusercontent.com/96044645/168053237-9bdc86fb-7ec3-42f2-a2d9-fc06042a41d8.png)
fixed
@Shoaibans
