### ISSUE TITLE
Collection name in link, title & Nav bar

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#32]
The name should be plural i.e. Headphones instead of headphone

![image](https://user-images.githubusercontent.com/97726944/168054234-93527868-eefc-46ca-848a-f1deceae8302.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
@Shoaibans 
![Uploading image.png…]()

**Comment by Shoaibans** [comment]
Remaining with the name in link
![image](https://user-images.githubusercontent.com/97726944/168078918-78492469-42f0-435b-bb45-dba8c5fab0c3.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans 
![image](https://user-images.githubusercontent.com/100207984/168347286-349b5f63-7b44-4b52-937a-e8c1ea2e6848.png)

**Comment by devAlokTripathi** [comment]
issue fixed.
