### ISSUE TITLE
2 currency converters

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#33]
The store is having 2 currency converters, one is fixed in footer & another one is floating.

![image](https://user-images.githubusercontent.com/97726944/168054524-8b36467b-35d7-4006-8a13-0458e2ea451f.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans issue fixed.
![image](https://user-images.githubusercontent.com/100207984/168346902-19b24e8f-2cca-4108-9096-f63cdcd7104f.png)
