### ISSUE TITLE
Pricing color combination

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#34]
In some of the products the pricing color is showing black while on some products the color is blue.

![image](https://user-images.githubusercontent.com/97726944/168055191-9b9d0187-6d9a-4592-8f25-d7d0149ca7f6.png)

**Comment by rajatsinghcedcoss** [comment]
![image](https://user-images.githubusercontent.com/96044645/168056462-9f21e090-edb5-4685-b885-6cc937415674.png)
fixed
@Shoaibans
