### ISSUE TITLE
Content in wishlist

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#37]
The content/ texts are coming very small in wishlist.
![image](https://user-images.githubusercontent.com/97726944/168065470-2c4fcae7-0cbd-4d09-b92a-13ef86a75df7.png)

**Comment by Shoaibans** [comment]
Still showing same at my end.
![image](https://user-images.githubusercontent.com/97726944/168208921-fa19028b-c65b-4173-92bc-140855037518.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
