### ISSUE TITLE
Extra spacing in product page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#38]
For some of the products, extra spacing is coming b/w the product main image & thumbnail images.
Ref link: https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/products/oupinke-retro-luxury-women-wristwatches-with-genuine-leather-strap-waterproof-quartz-with-calendar
![image](https://user-images.githubusercontent.com/97726944/168065885-9e2e5f7f-5c60-4a4c-af33-ddb4b7d5f4ee.png)

**Comment by rajatsinghcedcoss** [comment]
@Shoaibans 
client needs to resize image to same size
