### ISSUE TITLE
Products in New arrivals section in homepage

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#39]
The New arrival section in homepage is looking empty, if there is only 2 products for headphones then we can use other products than headphones in New arrivals section so that the area will not look empty.
![image](https://user-images.githubusercontent.com/97726944/168413830-bdc3a6fd-cda4-486f-877a-7b54b7a3ac42.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans fixed.
![image](https://user-images.githubusercontent.com/100207984/168867999-e89ebfcf-9410-447b-8df9-166dc272900a.png)
