### ISSUE TITLE
Name in link & Title

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#4]
The navigation menu is showing All collections but the link & the collection page title is showing only Collections.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/collections

![image](https://user-images.githubusercontent.com/97726944/167831815-80e65dd5-5620-4876-a1c6-f9e8ef5d8ed5.png)

**Comment by rajatsinghcedcoss** [comment]
fixed
![image](https://user-images.githubusercontent.com/96044645/168046517-4956bb14-ff22-42fa-84b1-41336cf96d01.png)
@Shoaibans
