### ISSUE TITLE
Validation overlapping

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#44]
The validation is overlapping with the input field in registration page.
![image](https://user-images.githubusercontent.com/97726944/170017497-03bee78c-cf94-4e2c-8ffd-dc705d86e6a0.png)

**Comment by rajatsinghcedcoss** [comment]
![image](https://user-images.githubusercontent.com/96044645/170027865-373df4bc-b081-44d3-9bdd-273190fbc303.png)
@Shoaibans
