### ISSUE TITLE
Products block size in Mac device

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#45]
The block size is coming extra long in mac device. (Safari browser)
Video: https://www.awesomescreenshot.com/video/9065864?key=2021f7446e99cf0617e8b651dbf1dcf2

**Comment by rajatsinghcedcoss** [comment]
![image](https://user-images.githubusercontent.com/96044645/170044279-13890faf-ba56-44ce-8639-85371971493b.png)
not coming in my end
