### ISSUE TITLE
Collection Issue

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#6]
The headphone collection page is having accessories products.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/collections/headphone

Video: https://www.awesomescreenshot.com/video/8844872?key=32f757c4995a6f93ffeb6e0e4225f673

**Comment by devAlokTripathi** [comment]
![image](https://user-images.githubusercontent.com/100207984/168382977-8c9cc403-b7d0-4510-8958-57759f1b0bb1.png)
@Shoaibans issue fixed but client need to uplaod product related to this name only 2 products are available.
