### ISSUE TITLE
Add to Cart button on the products in collection page is not working 

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#7]
The Add to Cart button on the products in collection page is not working after applying filters.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/collections/watches-1

Video: https://www.awesomescreenshot.com/video/8845101?key=aaf7703eab279c4871a87e9054bfd539

**Comment by devAlokTripathi** [comment]
@Shoaibans  fixed please check
