### ISSUE TITLE
Cursor on hover in filters

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#8]
The mouse cursor is coming while hovering to the filters. Hand cursor should come on hover

![image](https://user-images.githubusercontent.com/97726944/167836028-e9dee4cd-de9c-48d4-93d6-1de7502989fe.png)

**Comment by rajatsinghcedcoss** [comment]
Done

https://www.awesomescreenshot.com/video/8846297?key=945c3f7d2aa4dc41ba54abe997cf9d80
