### ISSUE TITLE
Email & phone no. in contact page

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Linda-Store-dev.#9]
The Email & no. is not clickable in contact page & also the content is not proper.
https://2yl4q5uvcgik4fw6-61850812586.shopifypreview.com/pages/contact-us

![image](https://user-images.githubusercontent.com/97726944/167836797-6c577bae-5365-4a41-a247-23b47c0314a1.png)

**Comment by devAlokTripathi** [comment]
email is clickable and please provide the content so we can put in this page @Shoaibans
![image](https://user-images.githubusercontent.com/100207984/168380460-abed7b2e-83ce-46a7-b0c7-f565d43b00ea.png)

**Comment by Shoaibans** [comment]
The mail is redirecting to page not found & the no. is not clickable.
Video: https://www.awesomescreenshot.com/video/8900597?key=c757cb832412d0d8b0e89927c7bef8cf
Reference for the content:
![image](https://user-images.githubusercontent.com/97726944/168413614-d8869369-568c-40f7-a3ff-03e5702c3120.png)

**Comment by devAlokTripathi** [comment]
@Shoaibans email is working please check and no. clickable not required.
